firstname = "Donovan"
lastname = "Avitia"
fullname = "Donovan Avitia Maldonado"
country = "Mexico"
city = "Aguascalientes"
age ="18"
year ="2025"
is_married = True
is_true = 1
is_light_on = 123
a,b,c,d = 1,2,3,4 
